### ISSUE TITLE
Break out "user docs" with simpler, screenshot-driven docs

### ISSUE THREAD

**Issue by postphotos** [gdpr-compliance/info#23]
We'd love a step-by-step tutorial on how to _actually use_ the thing. A video wouldn't hurt. (Maybe @kienstra has some time?!)

Give me a walk through on a dummy user - `johndoe@email.com` - and a request for erasure, export, etc. As well as the process to set up a website with a `privacy policy` using the .

See notes in [userdocs.md](https://github.com/gdpr-compliance/info/blob/master/userdocs.md) or from this [diff](https://github.com/gdpr-compliance/info/commit/38a8525c397f7102c37e676b305f48aea1338e65) if they're not there anymore.

**Comment by postphotos** [comment]
> To-do: Would be nice if we could add a "how-to-use" section by May 25 launch, see Woo article here doing a good job of this: https://woocommerce.wordpress.com/2018/05/04/woocommerce-3-4-gdpr-features/
The note from the `diff`.

**Comment by atachibana** [comment]
I will write those guide in Codex.

**Comment by atachibana** [comment]
Hi. I wrote this article for Settings => Privacy with help of @mirucon
https://codex.wordpress.org/Settings_Privacy_Screen
will follow  Exporter and Eraseer ... Any comments are welcome.

**Comment by postphotos** [comment]
Props @atachibana. I'll close this issue.

**Comment by atachibana** [comment]
Tools => Export Personal Data
https://codex.wordpress.org/Tools_Export_Personal_Data_Screen

**Comment by atachibana** [comment]
Tools => Erase Personal Data
https://codex.wordpress.org/Tools_Erace_Personal_Data_Screen
